In [ ]:
import numpy as np

var= np.array([1,2,3,4,5,3,2])
print("min :",np.min(var), np.argmin(var)) # for index 
print("max :",np.max(var), np.argmax(var))


arr1 = np.array([[1,2,3,4],[5,6,7,8]])

for i in arr1:
    for j in i:
        print("\n",j)


print("using nditer method")  

for i in np.nditer(arr1):
    print(i)


 
    


min : 1 0
max : 5 4

 1

 2

 3

 4

 5

 6

 7

 8


In [ ]:
# copy and view in numpy array

var= np.array([1,2,3,4])
co = var.copy()

print("var:", var)
print("copy:", co)




var: [1 2 3 4]
copy: [1 2 3 4]


In [9]:
xi= np.array([9,8,7,6.5])

vi = xi.view()
print("x", xi)

print("view :", vi)

x [9.  8.  7.  6.5]
view : [9.  8.  7.  6.5]


In [17]:
# shuffle

var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)


[1 2 4 5 3]


In [20]:
# Unique

var1 = np.array([1,2,3,4,5,6,7, 8 ,7])

x = np.unique(var1)
print(x)

[1 2 3 4 5 6 7 8]


In [23]:
# resize 

var2 = np.array([1,2,3,4,5,6,7,8,9])

y = np.resize(var2,(3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
