#this is a numpy chellange

In [13]:
import numpy as np


# creating array from list 

In [14]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)


arr_2d = np.array([[1, 2, 3,4], [4, 5, 6,8]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3 4]
 [4 5 6 8]]


# list vs numpy array


In [24]:
list_1 = [2,4,6,8]
print("list array multiplication", list_1*2)

nump_arr = np.array([2,3,4]) # element wise multiplication
print("numpy array multiplication", nump_arr*2)



list array multiplication [2, 4, 6, 8, 2, 4, 6, 8]
numpy array multiplication [4 6 8]


In [25]:
zeros = np.zeros((4,3))
print("creating arrays from zeros:", zeros)

ones = np.ones((4,2))
print("creeating  arrays frome ones", ones)

random = np.random.random((2,4))
print("creeating  arrays randomly", random)

full = np.full((3,4),9)
print("creeating  arrays randomly",full )

sequence = np.arange(0,10,3)
print("creeating  arrays sequently", sequence)

creating arrays from zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
creeating  arrays frome ones [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
creeating  arrays randomly [[0.69123084 0.68092191 0.66429249 0.63959034]
 [0.29237709 0.15380032 0.22888487 0.86864604]]
creeating  arrays randomly [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
creeating  arrays sequently [0 3 6 9]


#vector, matrix & tensor

In [32]:
vector = np.array([2,4,7])
print("vector is ", vector)

matrix = np.array([[2,4,7],
                   [5,8,9]])
print("matrix is is ", matrix)

tensor = np.array([[[2,4],[3,8]],
                    [[5,9],[7,13]]])
print("tensor is ",tensor)

vector is  [2 4 7]
matrix is is  [[2 4 7]
 [5 8 9]]
tensor is  [[[ 2  4]
  [ 3  8]]

 [[ 5  9]
  [ 7 13]]]


# array properties


In [33]:
arr = np.array([[2,3,7],[3,4,9]])

print("shape of array is",arr.shape)
print("array dimenssion is ", arr.ndim)
print("array size is", arr.size)
print("array data type is", arr.dtype)


shape of array is (2, 3)
array dimenssion is  2
array size is 6
array data type is int64


# Array Reshapig

In [40]:
arr_3 = np.arange(12)

print("\n original array", arr_3)

reshaped = arr_3.reshape(4,3)
print("\n reshaped  array", reshaped)

flattened = reshaped.flatten()
print("\n flattend  array", flattened)

raveled = reshaped.ravel()  # ravel returns view instead copy
print("\n raveled  array", raveled)


transpose = reshaped.T
print("\n transposed array is", transpose)


 original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped  array [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 flattend  array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled  array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array is [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
