# Numpy array operations

In [19]:
import numpy as np

In [20]:
arrey = np.array([1,2,3,4,5,6,7,8,9])

print("array basic slicing ",arrey[2:6])
print("array with step ",arrey[2:6:2])
print("negative indexing ",arrey[-4])



array basic slicing  [3 4 5 6]
array with step  [3 5]
negative indexing  6


In [21]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n specific element", arr[2,3])
print("\n Entire row", arr[1])
print("\n specific column", arr[:,3] )




 specific element 12

 Entire row [5 6 7 8]

 specific column [ 4  8 12]


# sorting

In [22]:
unsorted = np.array([1,3,2,5,7,9,8,4,6])
print("sorted array is ",np.sort(unsorted))

arr_2dunsorted = np.array([[3,1],[1,2],[2,3]])
print("\n sorted 2d array by row ",np.sort(arr_2dunsorted, axis=0))
print("\n sorted 2d array by column ",np.sort(arr_2dunsorted, axis=1))

sorted array is  [1 2 3 4 5 6 7 8 9]

 sorted 2d array by row  [[1 1]
 [2 2]
 [3 3]]

 sorted 2d array by column  [[1 3]
 [1 2]
 [2 3]]


# filter

In [23]:
numbers = np.array([1,2,7,4,5,6,7,9,8])

even = numbers[numbers %2 ==0]
print("even numbers are: ", even)

even numbers are:  [2 4 6 8]


# filters with mask

In [24]:
mask = numbers > 5

print("Numbers grater than 5", numbers[mask])

Numbers grater than 5 [7 6 7 9 8]


# Fancy indexing vs np.Where()

In [25]:
indice = [1,4,0]
print(numbers[indice])

where_result = np.where(numbers>4)
print("numbers where", numbers[where_result])

[2 5 1]
numbers where [7 5 6 7 9 8]


In [26]:
condition_arr = np.where(numbers>6, numbers*4, numbers)
print(condition_arr)

[ 1  2 28  4  5  6 28 36 32]


## Adding & removing Data 

In [27]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

combine = np.concatenate((arr_1, arr_2))
print("combination of arr_1 and arr_2 is ", combine)

combination of arr_1 and arr_2 is  [1 2 3 4 5 6 7 8]


## array compatibility

In [29]:
original= np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row)) # np.vstack add rows always
print("with new row " ,with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("with new column " ,with_new_col)

with new row  [[1 2]
 [3 4]
 [5 6]]
with new column  [[1 2 7]
 [3 4 8]]


In [30]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr, 2)
print("array after deletion ", deleted)


array after deletion  [1 2 4 5]
